Coding/WebIDE-Frontend

app/components/Pane/Pane.jsx
app/components/Pane/actions.js
app/components/Pane/reducer.js
app/components/Panel/Panel.jsx
app/components/Panel/PanelAxis.jsx
app/components/Panel/actions.js
app/components/Panel/reducer.js
app/components/ResizeBar.jsx

extract the resize bar component as common module

panel resize fix

---

app/components/Git/actions.js
app/initialize.js

Add modal, notify actions to window

---

app/components/Git/actions.js
app/components/Tab/reducer.js
app/components/Terminal/index.jsx
app/components/Terminal/terminal-client.js
app/utils/request.js

Fix term reconnection
Fix error msg while push and pull
Fix auth url

re-enable terminal event subscription, fix error in request.js

---

app/backendAPI/packageAPI.js
app/components/Package/actions.js
app/initialize.js
app/utils/request.js

增加插件hot reload支持

---

app/components/Git/actions.js
app/components/Git/modals/rebaseStart.jsx
app/components/Git/reducer.js

Fix show tags in rebase modal

---

app/backendAPI/fileAPI.js
app/components/Git/GitBranchWidget.jsx
app/components/Git/modals/resolveConflicts.jsx
app/components/Menu/MenuItem.jsx
app/styles/core-ui/GitMerge.styl
app/styles/core-ui/Menu.styl
app/utils/request.js

修复 fixes Coding/WebIDE#103 , Coding/WebIDE#106 上传文件失效问题

修复#103 ,#106 上传文件失效问题

---

app/backendAPI/gitAPI.js
app/commands/commandBindings/git.js
app/commands/commandBindings/misc.js
app/components/Git/actions.js
app/components/Git/modals/merge.jsx

Coding/WebIDE#130
Coding/WebIDE#131
Coding/WebIDE#124

Hackape/platform v2 alpha.2 bug fix

---

app/components/Setting/reducer.js
app/styles/main.styl

安装几个常用比较好用的code mirror theme，修复切换问题，本地语言问题，fixes  Coding/WebIDE#145

安装几个常用比较好用的code mirror theme

---

app/components/CodeMirrorEditor/index.jsx
app/components/FileTree/subscribeToFileChange.js
app/components/Tab/actions.js
app/components/Tab/reducer.js
app/components/Tab/selectors.js

令 codemirror editor tab 的内容响应 ws 事件做更新

---

app/commands/commandBindings/misc.js
app/components/Panel/PanelContent.jsx
app/components/Panel/SideBar.jsx
app/components/Panel/actions.js
app/components/Panel/reducer.js
app/components/Tab/TabBar.jsx
app/components/Tab/TabContainer.jsx
app/components/Tab/actions.js

Fix https://github.com/Coding/WebIDE/issues/95

---

app/components/Git/actions.js
app/components/Git/modals/stash.jsx
app/styles/core-ui/PanelAndPane.styl
app/styles/mixins/misc.styl
app/utils/promise.prototype.finalCatch.js
app/utils/request.js

fix Coding/WebIDE#170
fix Coding/WebIDE#157
fix Coding/WebIDE#167

address several bugs

---

app/commons/Pane/state.js
app/components/Pane/state.js

address Coding/WebIDE#180

---

app/components/Editor/EditorWrapper.jsx
app/components/Editor/codemirrorDefaultOptions.js
app/i18n/en_US/settings.json
app/i18n/zh_CN/settings.json
app/initialize/index.js
app/settings.js
app/utils/dynamicStyle.js

Editor settings

---

app/components/StatusBar/StatusBar.jsx
app/styles/core-ui/StatusBar.styl

add spacekey in statusbar

---

app/styles/core-ui/FileTree.styl

fix filetree style

---

app/styles/dark/styles/env.styl

update light theme

---

app/styles/base-theme/index.styl
app/styles/dark/index.styl
app/styles/dark/styles/notice.styl

update notice theme

---

app/components/MonacoEditor/state.js

fix empty editor

---

package.json
yarn.lock

fix jsonrpc-version

---

app/commands/commandBindings/file.js
app/components/Editor/components/EditorWidgets/EditorWidgets.jsx
app/components/Editor/components/EditorWidgets/ModeWidget.jsx
app/components/MenuBar/menuBarItems.jsx
app/components/MonacoEditor/Editors/CodeEditor.jsx
app/components/MonacoEditor/Editors/MarkDownEditor.jsx
app/components/MonacoEditor/Editors/createHelper.js
app/components/MonacoEditor/MonacoReact/BaseEditor.jsx
app/components/Setting/LanguageServerSetting.jsx
app/components/Setting/index.jsx
app/components/Setting/state.js
app/components/Tab/LanguageClientState.js
app/components/Tab/TabContainer.jsx
app/components/Tab/actions.js
app/config.js
app/i18n/en_US/settings.json
app/i18n/zh_CN/settings.json
app/settings.js

* 修改默认编辑器为新版编辑器，选项修改为切回旧版编辑器
* 修复 markdown 编辑器输入中文重复 rerender 导致光标出错的 bug
* 去掉语言服务器报错输出信息

Fix bug setting

---

app/components/Tab/LanguageClientState.js
app/settings.js

* 修改语言服务器自动连接逻辑
* 修改设置表单忽略初次修改 value 时触发 reaction 的行为

fix setting bug

---

app/components/MonacoEditor/Editors/CodeEditor.jsx
app/components/MonacoEditor/MonacoReact/BaseEditor.jsx
app/components/MonacoEditor/state.js
app/components/Tab/LanguageClientState.js
app/settings.js
package.json
yarn.lock

* 修改多个目录时语言服务器连接方式，改为单个websocket连接
* 通过lsp协议发送修改当前工作空间目录请求而非重新开启新线程

Fix languageclient

---

app/settings.js

Fix default theme

---

app/backendAPI/gitAPI.js
app/commands/commandBindings/git.js
app/components/MenuBar/menuBarItems.jsx
app/components/Modal/ResetRemote/index.js
app/components/Modal/modals/index.js
app/components/Modal/modals/modalCache.js
app/i18n/en_US/git.json
app/i18n/en_US/menuBarItems.json
app/i18n/zh_CN/git.json
app/i18n/zh_CN/menuBarItems.json

* 版本菜单添加 git 初始化功能
* 版本菜单添加重设 git remote 功能

add git init & git remote

---

app/components/Modal/ResetRemote/index.js

* 重设远端输入框添加 enter 事件
* 添加按钮 i18n

udpate i18n & keydown event

---

app/components/MenuBar/MenuBar.jsx
app/components/MenuBar/menuBarItems.jsx

fix menubar active bug

---

app/components/Editor/components/EditorWidgets/ModeWidget.jsx
app/components/MonacoEditor/Editors/MarkDownEditor.jsx
app/components/MonacoEditor/MonacoReact/BaseEditor.jsx
app/components/MonacoEditor/state.js
package.json
webpack_configs/common.config.js
webpack_configs/monaco-plugin-config/initialOptions.js
webpack_configs/webpack.prod.config.js

* 修复 markdown 预览切回的时候丢失编辑器的bug
* 修改 dev-server 内存参数
* 修改 webpack.config

fix md editor bug, fix config bug

---

.eslintrc
app/commands/commandBindings/git.js
app/components/Modal/GitCommitView/CommitFileList.js
app/components/Modal/GitCommitView/DiffView.js
app/components/Modal/GitCommitView/index.js
app/components/Modal/modals/index.js
app/components/Modal/modals/modalCache.js
app/components/MonacoEditor/MonacoReact/BaseDiffEditor.js
app/components/MonacoEditor/utils/modeInfos.js
app/i18n/en_US/git.json
app/i18n/zh_CN/git.json
app/settings.js
app/styles/core-ui/Git.styl
app/styles/dark/styles/modal.styl

* 添加 monaco-diff-editor
* 添加新版编辑器下 Git 提交界面
* 修复切回旧版编辑器代码高亮可能变默认配色的bug

Monaco diff view

---

.babelrc
package.json
yarn.lock

* 添加 @babel/plugin-transform-react-constant-elements 插件，生产环境提升 react 渲染性能

add @babel/plugin-transform-react-constant-elements

---

.eslintrc
app/backendAPI/projectAPI.js
app/components/Modal/CreateProject/CreateEmptyWs.js
app/components/Modal/CreateProject/ImportFromCoding.js
app/components/Modal/CreateProject/ImportFromGit.js
app/components/Modal/CreateProject/index.js
app/components/Modal/modals/index.js
app/components/Modal/modals/modalCache.js
app/i18n/en_US/index.js
app/i18n/en_US/modal.json
app/i18n/en_US/project.json
app/i18n/zh_CN/index.js
app/i18n/zh_CN/modal.json
app/i18n/zh_CN/project.json
app/styles/core-ui/Import.styl

* 修改从 Git/Coding 导入到新建 workspace 弹窗

Workspace menu

---

app/backendAPI/languageServerAPI.js
app/commons/File/actions.js
app/components/Setting/state.js
app/config.js
app/settings.js

update languageserver settings

---

app/components/MenuBar/menuBarItems.jsx
app/styles/core-ui/MenuBar.styl
app/styles/dark/styles/menu.styl

replace logo

---

app/components/MonacoEditor/state.js

fixi column/line error

---

app/components/MonacoEditor/Editors/MarkDownEditor.jsx

* 修改 markdown 编辑器不解析 html
* 去除无用的 marked

fix md error

---

app/components/Editor/components/EditorWidgets/ModeWidget.jsx
app/components/MonacoEditor/MonacoReact/BaseEditor.jsx
app/components/MonacoEditor/languages/clojure/clojure.contribution.js
app/components/MonacoEditor/languages/clojure/clojure.js
app/components/MonacoEditor/languages/index.js
app/components/MonacoEditor/languages/scheme/scheme.contribution.js
app/components/MonacoEditor/languages/scheme/scheme.js
app/components/MonacoEditor/languages/shell/shell.contribution.js
app/components/MonacoEditor/languages/shell/shell.js
app/components/MonacoEditor/state.js
app/components/MonacoEditor/utils/findLanguage.js
app/components/MonacoEditor/utils/modeInfos.js

* 添加 ShellScript、Clojure、Scheme 语言高亮

add shell script, clojure, scheme support

---

app/components/MonacoEditor/languages/index.js
app/components/MonacoEditor/languages/vue/vue.contribution.js
app/components/MonacoEditor/languages/vue/vue.js
app/components/MonacoEditor/utils/modeInfos.js
app/components/Tab/LanguageClientState.js

add vue highlight
